header: Services

intro: Take a look at all the opportunities and challenges I have to offer. Let's start your transformation through applied intention.

executivecoaching-intro: Let me provide a space to talk about your goals and plans. Together, we will work to determine the steps you will take to achieve them.

hundreddayjourney-intro: So much can be accomplished in just 100 days. The duration will allow us to focus on something important to you.

thousanddayjourney-intro: If a lot can be accomplished in 100 days, just imagine what 1000 days can do. This series of smaller 100 day journeys will help you achieve your plans.

emotionalintelligence-intro: EQ-i certified. Emotions help us learn new things, understand others, and push us to take action.

spice-intro: SPICE is an acronym to remember key contributors to happiness and a well-balanced life. <span class="bold">S</span>piritual, <span class="bold">P</span>hysical, <span class="bold">I</span>ntellectual, <span class="bold">C</span>reative, <span class="bold">E</span>motional.

motivationalspeaking-intro: I give motivational speeches on a variety of topics including resiliency and emotional intelligence.
