copyright: © 2018 Roz Ross. All rights reserved.

contact:
  tel: "+16138508928"
  tel_display: "+1 (613) 850-8928"
  email: "info@rozross.com"

location:
  map: "https://maps.google.ca/?q=Ottawa,+ON"
  locality: "Ottawa"
  region: "ON"
