backend:
  name: github
  repo: AlexSpagnuolo/rozross

media_folder: "images/uploads"

collections:
  - name: "website-settings"
    label: "Website settings"
    files:
      - label: "Website settings"
        name: "site"
        file: "_data/site.yml"
        fields:
          - label: "Contact"
            name: "contact"
            widget: "object"
            fields:
            - label: "Telephone number"
              name: "tel"
              widget: "string"
            - label: "Telephone display number"
              name: "tel_display"
              widget: "string"
            - label: "Email"
              name: "email"
              widget: "string"

          - label: "Location"
            name: "location"
            widget: "object"
            fields:
              - label: "Locality"
                name: "locality"
                widget: "string"
              - label: "Region"
                name: "region"
                widget: "string"
