backend:
  name: github
  repo: AlexSpagnuolo/rozross

media_folder: "images/uploads"

collections:
  - label: "Website settings"
    name: "website-settings"
    files:
      - label: "Website settings"
        name: "site"
        file: "_data/site.yml"
        fields:
          - label: "Contact"
            name: "contact"
            widget: "object"
            fields:
              - label: "Telephone number"
                name: "tel"
                widget: "string"
              - label: "Telephone display number"
                name: "tel_display"
                widget: "string"
              - label: "Email"
                name: "email"
                widget: "string"
          - label: "Location"
            name: "location"
            widget: "object"
            fields:
              - label: "Locality"
                name: "locality"
                widget: "string"
              - label: "Region"
                name: "region"
                widget: "string"
          - label: "Copyright"
            name: "copyright"
            widget: "string"

  - label: "Pages"
    name: "pages"
    files:
      - label: "Home page"
        name: "home"
        file: "_data/home.yml"
        fields:
          - label: "Hook"
            name: "hook"
            widget: "string"
          - label: "Introduction"
            name: "intro"
            widget: "string"
          - label: "Client testimonial quote"
            name: "testimonial"
            widget: "text"
          - label: "Client testimonial name"
            name: "testimonial-name"
            widget: "string"
      - label: "About page"
        name: "about"
        file: "_data/about.yml"
        fields:
          - label: "Header"
            name: "header"
            widget: "string"
          - label: "Introduction"
            name: "intro"
            widget: "text"
          - label: "Biography"
            name: "bio"
            widget: "text"
          - label: "Quotation"
            name: "quotation"
            widget: "object"
            fields:
              - label: "Quote"
                name: "quote"
                widget: "string"
              - label: "Quote Description"
                name: "quote-desc"
                widget: "string"
          - label: "Client Testimonials"
            name: "testimonials"
            widget: "object"
            fields:
              - label: "Client Testimonial 1"
                name: "testimonial1"
                widget: "text"
              - label: "Client Testimonial Name 1"
                name: "testimonial-name1"
                widget: "string"
              - label: "Client Testimonial 2"
                name: "testimonial2"
                widget: "text"
              - label: "Client Testimonial Name 2"
                name: "testimonial-name2"
                widget: "string"
      - label: "Services page"
        name: "services"
        file: "_data/services.yml"
        fields:
          - label: "Header"
            name: "header"
            widget: "string"
          - label: "Introduction"
            name: "intro"
            widget: "string"
          - label: "Executive Coaching Introduction"
            name: "executivecoaching-intro"
            widget: "string"
          - label: "100 Day Journey Introduction"
            name: "hundreddayjourney-intro"
            widget: "string"
          - label: "1000 Day Journey Introduction"
            name: "thousanddayjourney-intro"
            widget: "string"
          - label: "Emotional Intelligence Reports & Coaching Introduction"
            name: "emotionalintelligence-intro"
            widget: "string"
          - label: "SPICE Resiliency Program Introduction"
            name: "spice-intro"
            widget: "string"
          - label: "Motivational Speaking Introduction"
            name: "motivationalspeaking-intro"
            widget: "string"
  - label: "Blog posts"
    name: "blog-posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "blog-post"
      - label: "Blog button featured image"
        name: "featuredimg"
        widget: "image"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Date"
        name: "postdate"
        widget: "string"
      - label: "Introduction"
        name: "introduction"
        widget: "string"
      - label: "Body"
        name: "body"
        widget: "markdown"
