backend:
  name: github
  repo: AlexSpagnuolo/rozross

media_folder: "images/uploads"

collections:
  - label: "Website settings"
    name: "website-settings"
    files:
      - label: "Website settings"
        name: "site"
        file: "_data/site.yml"
        fields:
          - label: "Contact"
            name: "contact"
            widget: "object"
            fields:
              - label: "Telephone number"
                name: "tel"
                widget: "string"
              - label: "Telephone display number"
                name: "tel_display"
                widget: "string"
              - label: "Email"
                name: "email"
                widget: "string"
          - label: "Location"
            name: "location"
            widget: "object"
            fields:
              - label: "Locality"
                name: "locality"
                widget: "string"
              - label: "Region"
                name: "region"
                widget: "string"
          - label: "Copyright"
            name: "copyright"
            widget: "string"

  - label: "Pages"
    name: "pages"
    files:
      - label: "Home page"
        name: "home"
        file: "_data/home.yml"
        fields:
          - label: "Hook"
            name: "hook"
            widget: "string"
          - label: "Introduction"
            name: "intro"
            widget: "string"
          - label: "Client testimonial quote"
            name: "testimonial"
            widget: "string"
          - label: "Client testimonial name"
            name: "testimonial-name"
            widget: "string"
      - label: "About page"
        name: "about"
        file: "_data/about.yml"
        fields:
          - label: "Header"
            name: "header"
            widget: "string"
          - label: "Introduction"
            name: "intro"
            widget: "string"
          - label: "Biography"
            name: "bio"
            widget: "text"
          - label: "Quote"
            name: "quote"
            widget: "object"
            fields:
              - label: "Quote"
                name: "quote"
                widget: "string"
              - label: "Quote Description"
                name: "quote-desc"
                widget: "string"

  - label: "Blog posts"
    name: "blog-posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "blog-post"
      - label: "Blog button featured image"
        name: "featuredimg"
        widget: "image"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Date"
        name: "postdate"
        widget: "string"
      - label: "Introduction"
        name: "introduction"
        widget: "string"
      - label: "Body"
        name: "body"
        widget: "markdown"
